/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: riak_kv.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "riak_kv.pb-c.h"
void   rpb_get_client_id_resp__init
                     (RpbGetClientIdResp         *message)
{
  static RpbGetClientIdResp init_value = RPB_GET_CLIENT_ID_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_client_id_resp__get_packed_size
                     (const RpbGetClientIdResp *message)
{
  assert(message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_client_id_resp__pack
                     (const RpbGetClientIdResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_client_id_resp__pack_to_buffer
                     (const RpbGetClientIdResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetClientIdResp *
       rpb_get_client_id_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetClientIdResp *)
     protobuf_c_message_unpack (&rpb_get_client_id_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_client_id_resp__free_unpacked
                     (RpbGetClientIdResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_set_client_id_req__init
                     (RpbSetClientIdReq         *message)
{
  static RpbSetClientIdReq init_value = RPB_SET_CLIENT_ID_REQ__INIT;
  *message = init_value;
}
size_t rpb_set_client_id_req__get_packed_size
                     (const RpbSetClientIdReq *message)
{
  assert(message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_set_client_id_req__pack
                     (const RpbSetClientIdReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_set_client_id_req__pack_to_buffer
                     (const RpbSetClientIdReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSetClientIdReq *
       rpb_set_client_id_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSetClientIdReq *)
     protobuf_c_message_unpack (&rpb_set_client_id_req__descriptor,
                                allocator, len, data);
}
void   rpb_set_client_id_req__free_unpacked
                     (RpbSetClientIdReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_set_client_id_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_req__init
                     (RpbGetReq         *message)
{
  static RpbGetReq init_value = RPB_GET_REQ__INIT;
  *message = init_value;
}
size_t rpb_get_req__get_packed_size
                     (const RpbGetReq *message)
{
  assert(message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_req__pack
                     (const RpbGetReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_req__pack_to_buffer
                     (const RpbGetReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetReq *
       rpb_get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetReq *)
     protobuf_c_message_unpack (&rpb_get_req__descriptor,
                                allocator, len, data);
}
void   rpb_get_req__free_unpacked
                     (RpbGetReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_resp__init
                     (RpbGetResp         *message)
{
  static RpbGetResp init_value = RPB_GET_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_resp__get_packed_size
                     (const RpbGetResp *message)
{
  assert(message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_resp__pack
                     (const RpbGetResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_resp__pack_to_buffer
                     (const RpbGetResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetResp *
       rpb_get_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetResp *)
     protobuf_c_message_unpack (&rpb_get_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_resp__free_unpacked
                     (RpbGetResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_get_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_put_req__init
                     (RpbPutReq         *message)
{
  static RpbPutReq init_value = RPB_PUT_REQ__INIT;
  *message = init_value;
}
size_t rpb_put_req__get_packed_size
                     (const RpbPutReq *message)
{
  assert(message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_put_req__pack
                     (const RpbPutReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_put_req__pack_to_buffer
                     (const RpbPutReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbPutReq *
       rpb_put_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbPutReq *)
     protobuf_c_message_unpack (&rpb_put_req__descriptor,
                                allocator, len, data);
}
void   rpb_put_req__free_unpacked
                     (RpbPutReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_put_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_put_resp__init
                     (RpbPutResp         *message)
{
  static RpbPutResp init_value = RPB_PUT_RESP__INIT;
  *message = init_value;
}
size_t rpb_put_resp__get_packed_size
                     (const RpbPutResp *message)
{
  assert(message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_put_resp__pack
                     (const RpbPutResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_put_resp__pack_to_buffer
                     (const RpbPutResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbPutResp *
       rpb_put_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbPutResp *)
     protobuf_c_message_unpack (&rpb_put_resp__descriptor,
                                allocator, len, data);
}
void   rpb_put_resp__free_unpacked
                     (RpbPutResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_put_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_del_req__init
                     (RpbDelReq         *message)
{
  static RpbDelReq init_value = RPB_DEL_REQ__INIT;
  *message = init_value;
}
size_t rpb_del_req__get_packed_size
                     (const RpbDelReq *message)
{
  assert(message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_del_req__pack
                     (const RpbDelReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_del_req__pack_to_buffer
                     (const RpbDelReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbDelReq *
       rpb_del_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbDelReq *)
     protobuf_c_message_unpack (&rpb_del_req__descriptor,
                                allocator, len, data);
}
void   rpb_del_req__free_unpacked
                     (RpbDelReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_del_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_buckets_req__init
                     (RpbListBucketsReq         *message)
{
  static RpbListBucketsReq init_value = RPB_LIST_BUCKETS_REQ__INIT;
  *message = init_value;
}
size_t rpb_list_buckets_req__get_packed_size
                     (const RpbListBucketsReq *message)
{
  assert(message->base.descriptor == &rpb_list_buckets_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_buckets_req__pack
                     (const RpbListBucketsReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_list_buckets_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_buckets_req__pack_to_buffer
                     (const RpbListBucketsReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_list_buckets_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListBucketsReq *
       rpb_list_buckets_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListBucketsReq *)
     protobuf_c_message_unpack (&rpb_list_buckets_req__descriptor,
                                allocator, len, data);
}
void   rpb_list_buckets_req__free_unpacked
                     (RpbListBucketsReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_list_buckets_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_buckets_resp__init
                     (RpbListBucketsResp         *message)
{
  static RpbListBucketsResp init_value = RPB_LIST_BUCKETS_RESP__INIT;
  *message = init_value;
}
size_t rpb_list_buckets_resp__get_packed_size
                     (const RpbListBucketsResp *message)
{
  assert(message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_buckets_resp__pack
                     (const RpbListBucketsResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_buckets_resp__pack_to_buffer
                     (const RpbListBucketsResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListBucketsResp *
       rpb_list_buckets_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListBucketsResp *)
     protobuf_c_message_unpack (&rpb_list_buckets_resp__descriptor,
                                allocator, len, data);
}
void   rpb_list_buckets_resp__free_unpacked
                     (RpbListBucketsResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_keys_req__init
                     (RpbListKeysReq         *message)
{
  static RpbListKeysReq init_value = RPB_LIST_KEYS_REQ__INIT;
  *message = init_value;
}
size_t rpb_list_keys_req__get_packed_size
                     (const RpbListKeysReq *message)
{
  assert(message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_keys_req__pack
                     (const RpbListKeysReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_keys_req__pack_to_buffer
                     (const RpbListKeysReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListKeysReq *
       rpb_list_keys_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListKeysReq *)
     protobuf_c_message_unpack (&rpb_list_keys_req__descriptor,
                                allocator, len, data);
}
void   rpb_list_keys_req__free_unpacked
                     (RpbListKeysReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_list_keys_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_keys_resp__init
                     (RpbListKeysResp         *message)
{
  static RpbListKeysResp init_value = RPB_LIST_KEYS_RESP__INIT;
  *message = init_value;
}
size_t rpb_list_keys_resp__get_packed_size
                     (const RpbListKeysResp *message)
{
  assert(message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_keys_resp__pack
                     (const RpbListKeysResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_keys_resp__pack_to_buffer
                     (const RpbListKeysResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListKeysResp *
       rpb_list_keys_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListKeysResp *)
     protobuf_c_message_unpack (&rpb_list_keys_resp__descriptor,
                                allocator, len, data);
}
void   rpb_list_keys_resp__free_unpacked
                     (RpbListKeysResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_list_keys_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_map_red_req__init
                     (RpbMapRedReq         *message)
{
  static RpbMapRedReq init_value = RPB_MAP_RED_REQ__INIT;
  *message = init_value;
}
size_t rpb_map_red_req__get_packed_size
                     (const RpbMapRedReq *message)
{
  assert(message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_map_red_req__pack
                     (const RpbMapRedReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_map_red_req__pack_to_buffer
                     (const RpbMapRedReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbMapRedReq *
       rpb_map_red_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbMapRedReq *)
     protobuf_c_message_unpack (&rpb_map_red_req__descriptor,
                                allocator, len, data);
}
void   rpb_map_red_req__free_unpacked
                     (RpbMapRedReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_map_red_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_map_red_resp__init
                     (RpbMapRedResp         *message)
{
  static RpbMapRedResp init_value = RPB_MAP_RED_RESP__INIT;
  *message = init_value;
}
size_t rpb_map_red_resp__get_packed_size
                     (const RpbMapRedResp *message)
{
  assert(message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_map_red_resp__pack
                     (const RpbMapRedResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_map_red_resp__pack_to_buffer
                     (const RpbMapRedResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbMapRedResp *
       rpb_map_red_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbMapRedResp *)
     protobuf_c_message_unpack (&rpb_map_red_resp__descriptor,
                                allocator, len, data);
}
void   rpb_map_red_resp__free_unpacked
                     (RpbMapRedResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_map_red_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_index_req__init
                     (RpbIndexReq         *message)
{
  static RpbIndexReq init_value = RPB_INDEX_REQ__INIT;
  *message = init_value;
}
size_t rpb_index_req__get_packed_size
                     (const RpbIndexReq *message)
{
  assert(message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_index_req__pack
                     (const RpbIndexReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_index_req__pack_to_buffer
                     (const RpbIndexReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbIndexReq *
       rpb_index_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbIndexReq *)
     protobuf_c_message_unpack (&rpb_index_req__descriptor,
                                allocator, len, data);
}
void   rpb_index_req__free_unpacked
                     (RpbIndexReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_index_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_index_resp__init
                     (RpbIndexResp         *message)
{
  static RpbIndexResp init_value = RPB_INDEX_RESP__INIT;
  *message = init_value;
}
size_t rpb_index_resp__get_packed_size
                     (const RpbIndexResp *message)
{
  assert(message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_index_resp__pack
                     (const RpbIndexResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_index_resp__pack_to_buffer
                     (const RpbIndexResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbIndexResp *
       rpb_index_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbIndexResp *)
     protobuf_c_message_unpack (&rpb_index_resp__descriptor,
                                allocator, len, data);
}
void   rpb_index_resp__free_unpacked
                     (RpbIndexResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_index_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_csbucket_req__init
                     (RpbCSBucketReq         *message)
{
  static RpbCSBucketReq init_value = RPB_CSBUCKET_REQ__INIT;
  *message = init_value;
}
size_t rpb_csbucket_req__get_packed_size
                     (const RpbCSBucketReq *message)
{
  assert(message->base.descriptor == &rpb_csbucket_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_csbucket_req__pack
                     (const RpbCSBucketReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_csbucket_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_csbucket_req__pack_to_buffer
                     (const RpbCSBucketReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_csbucket_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCSBucketReq *
       rpb_csbucket_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCSBucketReq *)
     protobuf_c_message_unpack (&rpb_csbucket_req__descriptor,
                                allocator, len, data);
}
void   rpb_csbucket_req__free_unpacked
                     (RpbCSBucketReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_csbucket_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_csbucket_resp__init
                     (RpbCSBucketResp         *message)
{
  static RpbCSBucketResp init_value = RPB_CSBUCKET_RESP__INIT;
  *message = init_value;
}
size_t rpb_csbucket_resp__get_packed_size
                     (const RpbCSBucketResp *message)
{
  assert(message->base.descriptor == &rpb_csbucket_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_csbucket_resp__pack
                     (const RpbCSBucketResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_csbucket_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_csbucket_resp__pack_to_buffer
                     (const RpbCSBucketResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_csbucket_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCSBucketResp *
       rpb_csbucket_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCSBucketResp *)
     protobuf_c_message_unpack (&rpb_csbucket_resp__descriptor,
                                allocator, len, data);
}
void   rpb_csbucket_resp__free_unpacked
                     (RpbCSBucketResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_csbucket_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_index_object__init
                     (RpbIndexObject         *message)
{
  static RpbIndexObject init_value = RPB_INDEX_OBJECT__INIT;
  *message = init_value;
}
size_t rpb_index_object__get_packed_size
                     (const RpbIndexObject *message)
{
  assert(message->base.descriptor == &rpb_index_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_index_object__pack
                     (const RpbIndexObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_index_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_index_object__pack_to_buffer
                     (const RpbIndexObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_index_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbIndexObject *
       rpb_index_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbIndexObject *)
     protobuf_c_message_unpack (&rpb_index_object__descriptor,
                                allocator, len, data);
}
void   rpb_index_object__free_unpacked
                     (RpbIndexObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_index_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_content__init
                     (RpbContent         *message)
{
  static RpbContent init_value = RPB_CONTENT__INIT;
  *message = init_value;
}
size_t rpb_content__get_packed_size
                     (const RpbContent *message)
{
  assert(message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_content__pack
                     (const RpbContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_content__pack_to_buffer
                     (const RpbContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbContent *
       rpb_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbContent *)
     protobuf_c_message_unpack (&rpb_content__descriptor,
                                allocator, len, data);
}
void   rpb_content__free_unpacked
                     (RpbContent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_link__init
                     (RpbLink         *message)
{
  static RpbLink init_value = RPB_LINK__INIT;
  *message = init_value;
}
size_t rpb_link__get_packed_size
                     (const RpbLink *message)
{
  assert(message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_link__pack
                     (const RpbLink *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_link__pack_to_buffer
                     (const RpbLink *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbLink *
       rpb_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbLink *)
     protobuf_c_message_unpack (&rpb_link__descriptor,
                                allocator, len, data);
}
void   rpb_link__free_unpacked
                     (RpbLink *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_counter_update_req__init
                     (RpbCounterUpdateReq         *message)
{
  static RpbCounterUpdateReq init_value = RPB_COUNTER_UPDATE_REQ__INIT;
  *message = init_value;
}
size_t rpb_counter_update_req__get_packed_size
                     (const RpbCounterUpdateReq *message)
{
  assert(message->base.descriptor == &rpb_counter_update_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_counter_update_req__pack
                     (const RpbCounterUpdateReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_counter_update_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_counter_update_req__pack_to_buffer
                     (const RpbCounterUpdateReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_counter_update_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCounterUpdateReq *
       rpb_counter_update_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCounterUpdateReq *)
     protobuf_c_message_unpack (&rpb_counter_update_req__descriptor,
                                allocator, len, data);
}
void   rpb_counter_update_req__free_unpacked
                     (RpbCounterUpdateReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_counter_update_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_counter_update_resp__init
                     (RpbCounterUpdateResp         *message)
{
  static RpbCounterUpdateResp init_value = RPB_COUNTER_UPDATE_RESP__INIT;
  *message = init_value;
}
size_t rpb_counter_update_resp__get_packed_size
                     (const RpbCounterUpdateResp *message)
{
  assert(message->base.descriptor == &rpb_counter_update_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_counter_update_resp__pack
                     (const RpbCounterUpdateResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_counter_update_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_counter_update_resp__pack_to_buffer
                     (const RpbCounterUpdateResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_counter_update_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCounterUpdateResp *
       rpb_counter_update_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCounterUpdateResp *)
     protobuf_c_message_unpack (&rpb_counter_update_resp__descriptor,
                                allocator, len, data);
}
void   rpb_counter_update_resp__free_unpacked
                     (RpbCounterUpdateResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_counter_update_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_counter_get_req__init
                     (RpbCounterGetReq         *message)
{
  static RpbCounterGetReq init_value = RPB_COUNTER_GET_REQ__INIT;
  *message = init_value;
}
size_t rpb_counter_get_req__get_packed_size
                     (const RpbCounterGetReq *message)
{
  assert(message->base.descriptor == &rpb_counter_get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_counter_get_req__pack
                     (const RpbCounterGetReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_counter_get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_counter_get_req__pack_to_buffer
                     (const RpbCounterGetReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_counter_get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCounterGetReq *
       rpb_counter_get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCounterGetReq *)
     protobuf_c_message_unpack (&rpb_counter_get_req__descriptor,
                                allocator, len, data);
}
void   rpb_counter_get_req__free_unpacked
                     (RpbCounterGetReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_counter_get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_counter_get_resp__init
                     (RpbCounterGetResp         *message)
{
  static RpbCounterGetResp init_value = RPB_COUNTER_GET_RESP__INIT;
  *message = init_value;
}
size_t rpb_counter_get_resp__get_packed_size
                     (const RpbCounterGetResp *message)
{
  assert(message->base.descriptor == &rpb_counter_get_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_counter_get_resp__pack
                     (const RpbCounterGetResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_counter_get_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_counter_get_resp__pack_to_buffer
                     (const RpbCounterGetResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_counter_get_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbCounterGetResp *
       rpb_counter_get_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbCounterGetResp *)
     protobuf_c_message_unpack (&rpb_counter_get_resp__descriptor,
                                allocator, len, data);
}
void   rpb_counter_get_resp__free_unpacked
                     (RpbCounterGetResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_counter_get_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpb_get_client_id_resp__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbGetClientIdResp, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_client_id_resp__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange rpb_get_client_id_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_get_client_id_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetClientIdResp",
  "RpbGetClientIdResp",
  "RpbGetClientIdResp",
  "",
  sizeof(RpbGetClientIdResp),
  1,
  rpb_get_client_id_resp__field_descriptors,
  rpb_get_client_id_resp__field_indices_by_name,
  1,  rpb_get_client_id_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_client_id_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_set_client_id_req__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbSetClientIdReq, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_set_client_id_req__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange rpb_set_client_id_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_set_client_id_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSetClientIdReq",
  "RpbSetClientIdReq",
  "RpbSetClientIdReq",
  "",
  sizeof(RpbSetClientIdReq),
  1,
  rpb_set_client_id_req__field_descriptors,
  rpb_set_client_id_req__field_indices_by_name,
  1,  rpb_set_client_id_req__number_ranges,
  (ProtobufCMessageInit) rpb_set_client_id_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_req__field_descriptors[13] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbGetReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbGetReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbGetReq, has_r),
    offsetof(RpbGetReq, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbGetReq, has_pr),
    offsetof(RpbGetReq, pr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basic_quorum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetReq, has_basic_quorum),
    offsetof(RpbGetReq, basic_quorum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notfound_ok",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetReq, has_notfound_ok),
    offsetof(RpbGetReq, notfound_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_modified",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbGetReq, has_if_modified),
    offsetof(RpbGetReq, if_modified),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "head",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetReq, has_head),
    offsetof(RpbGetReq, head),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deletedvclock",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetReq, has_deletedvclock),
    offsetof(RpbGetReq, deletedvclock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbGetReq, has_timeout),
    offsetof(RpbGetReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sloppy_quorum",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetReq, has_sloppy_quorum),
    offsetof(RpbGetReq, sloppy_quorum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbGetReq, has_n_val),
    offsetof(RpbGetReq, n_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbGetReq, has_type),
    offsetof(RpbGetReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_req__field_indices_by_name[] = {
  4,   /* field[4] = basic_quorum */
  0,   /* field[0] = bucket */
  8,   /* field[8] = deletedvclock */
  7,   /* field[7] = head */
  6,   /* field[6] = if_modified */
  1,   /* field[1] = key */
  11,   /* field[11] = n_val */
  5,   /* field[5] = notfound_ok */
  3,   /* field[3] = pr */
  2,   /* field[2] = r */
  10,   /* field[10] = sloppy_quorum */
  9,   /* field[9] = timeout */
  12,   /* field[12] = type */
};
static const ProtobufCIntRange rpb_get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor rpb_get_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetReq",
  "RpbGetReq",
  "RpbGetReq",
  "",
  sizeof(RpbGetReq),
  13,
  rpb_get_req__field_descriptors,
  rpb_get_req__field_indices_by_name,
  1,  rpb_get_req__number_ranges,
  (ProtobufCMessageInit) rpb_get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_resp__field_descriptors[3] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbGetResp, n_content),
    offsetof(RpbGetResp, content),
    &rpb_content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbGetResp, has_vclock),
    offsetof(RpbGetResp, vclock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unchanged",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbGetResp, has_unchanged),
    offsetof(RpbGetResp, unchanged),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_resp__field_indices_by_name[] = {
  0,   /* field[0] = content */
  2,   /* field[2] = unchanged */
  1,   /* field[1] = vclock */
};
static const ProtobufCIntRange rpb_get_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_get_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetResp",
  "RpbGetResp",
  "RpbGetResp",
  "",
  sizeof(RpbGetResp),
  3,
  rpb_get_resp__field_descriptors,
  rpb_get_resp__field_indices_by_name,
  1,  rpb_get_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_put_req__field_descriptors[16] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbPutReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbPutReq, has_key),
    offsetof(RpbPutReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbPutReq, has_vclock),
    offsetof(RpbPutReq, vclock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpbPutReq, content),
    &rpb_content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbPutReq, has_w),
    offsetof(RpbPutReq, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbPutReq, has_dw),
    offsetof(RpbPutReq, dw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_body",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_return_body),
    offsetof(RpbPutReq, return_body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbPutReq, has_pw),
    offsetof(RpbPutReq, pw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_not_modified",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_if_not_modified),
    offsetof(RpbPutReq, if_not_modified),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_none_match",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_if_none_match),
    offsetof(RpbPutReq, if_none_match),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_head",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_return_head),
    offsetof(RpbPutReq, return_head),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbPutReq, has_timeout),
    offsetof(RpbPutReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asis",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_asis),
    offsetof(RpbPutReq, asis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sloppy_quorum",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbPutReq, has_sloppy_quorum),
    offsetof(RpbPutReq, sloppy_quorum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbPutReq, has_n_val),
    offsetof(RpbPutReq, n_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbPutReq, has_type),
    offsetof(RpbPutReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_put_req__field_indices_by_name[] = {
  12,   /* field[12] = asis */
  0,   /* field[0] = bucket */
  3,   /* field[3] = content */
  5,   /* field[5] = dw */
  9,   /* field[9] = if_none_match */
  8,   /* field[8] = if_not_modified */
  1,   /* field[1] = key */
  14,   /* field[14] = n_val */
  7,   /* field[7] = pw */
  6,   /* field[6] = return_body */
  10,   /* field[10] = return_head */
  13,   /* field[13] = sloppy_quorum */
  11,   /* field[11] = timeout */
  15,   /* field[15] = type */
  2,   /* field[2] = vclock */
  4,   /* field[4] = w */
};
static const ProtobufCIntRange rpb_put_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor rpb_put_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbPutReq",
  "RpbPutReq",
  "RpbPutReq",
  "",
  sizeof(RpbPutReq),
  16,
  rpb_put_req__field_descriptors,
  rpb_put_req__field_indices_by_name,
  1,  rpb_put_req__number_ranges,
  (ProtobufCMessageInit) rpb_put_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_put_resp__field_descriptors[3] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbPutResp, n_content),
    offsetof(RpbPutResp, content),
    &rpb_content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbPutResp, has_vclock),
    offsetof(RpbPutResp, vclock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbPutResp, has_key),
    offsetof(RpbPutResp, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_put_resp__field_indices_by_name[] = {
  0,   /* field[0] = content */
  2,   /* field[2] = key */
  1,   /* field[1] = vclock */
};
static const ProtobufCIntRange rpb_put_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_put_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbPutResp",
  "RpbPutResp",
  "RpbPutResp",
  "",
  sizeof(RpbPutResp),
  3,
  rpb_put_resp__field_descriptors,
  rpb_put_resp__field_indices_by_name,
  1,  rpb_put_resp__number_ranges,
  (ProtobufCMessageInit) rpb_put_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_del_req__field_descriptors[13] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbDelReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbDelReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rw",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_rw),
    offsetof(RpbDelReq, rw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbDelReq, has_vclock),
    offsetof(RpbDelReq, vclock),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_r),
    offsetof(RpbDelReq, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_w),
    offsetof(RpbDelReq, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_pr),
    offsetof(RpbDelReq, pr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_pw),
    offsetof(RpbDelReq, pw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_dw),
    offsetof(RpbDelReq, dw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_timeout),
    offsetof(RpbDelReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sloppy_quorum",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbDelReq, has_sloppy_quorum),
    offsetof(RpbDelReq, sloppy_quorum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbDelReq, has_n_val),
    offsetof(RpbDelReq, n_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbDelReq, has_type),
    offsetof(RpbDelReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_del_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  8,   /* field[8] = dw */
  1,   /* field[1] = key */
  11,   /* field[11] = n_val */
  6,   /* field[6] = pr */
  7,   /* field[7] = pw */
  4,   /* field[4] = r */
  2,   /* field[2] = rw */
  10,   /* field[10] = sloppy_quorum */
  9,   /* field[9] = timeout */
  12,   /* field[12] = type */
  3,   /* field[3] = vclock */
  5,   /* field[5] = w */
};
static const ProtobufCIntRange rpb_del_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor rpb_del_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbDelReq",
  "RpbDelReq",
  "RpbDelReq",
  "",
  sizeof(RpbDelReq),
  13,
  rpb_del_req__field_descriptors,
  rpb_del_req__field_indices_by_name,
  1,  rpb_del_req__number_ranges,
  (ProtobufCMessageInit) rpb_del_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_buckets_req__field_descriptors[3] =
{
  {
    "timeout",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbListBucketsReq, has_timeout),
    offsetof(RpbListBucketsReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbListBucketsReq, has_stream),
    offsetof(RpbListBucketsReq, stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbListBucketsReq, has_type),
    offsetof(RpbListBucketsReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_buckets_req__field_indices_by_name[] = {
  1,   /* field[1] = stream */
  0,   /* field[0] = timeout */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange rpb_list_buckets_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_list_buckets_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListBucketsReq",
  "RpbListBucketsReq",
  "RpbListBucketsReq",
  "",
  sizeof(RpbListBucketsReq),
  3,
  rpb_list_buckets_req__field_descriptors,
  rpb_list_buckets_req__field_indices_by_name,
  1,  rpb_list_buckets_req__number_ranges,
  (ProtobufCMessageInit) rpb_list_buckets_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_buckets_resp__field_descriptors[2] =
{
  {
    "buckets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbListBucketsResp, n_buckets),
    offsetof(RpbListBucketsResp, buckets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbListBucketsResp, has_done),
    offsetof(RpbListBucketsResp, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_buckets_resp__field_indices_by_name[] = {
  0,   /* field[0] = buckets */
  1,   /* field[1] = done */
};
static const ProtobufCIntRange rpb_list_buckets_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_list_buckets_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListBucketsResp",
  "RpbListBucketsResp",
  "RpbListBucketsResp",
  "",
  sizeof(RpbListBucketsResp),
  2,
  rpb_list_buckets_resp__field_descriptors,
  rpb_list_buckets_resp__field_indices_by_name,
  1,  rpb_list_buckets_resp__number_ranges,
  (ProtobufCMessageInit) rpb_list_buckets_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_keys_req__field_descriptors[3] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbListKeysReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbListKeysReq, has_timeout),
    offsetof(RpbListKeysReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbListKeysReq, has_type),
    offsetof(RpbListKeysReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_keys_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  1,   /* field[1] = timeout */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange rpb_list_keys_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_list_keys_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListKeysReq",
  "RpbListKeysReq",
  "RpbListKeysReq",
  "",
  sizeof(RpbListKeysReq),
  3,
  rpb_list_keys_req__field_descriptors,
  rpb_list_keys_req__field_indices_by_name,
  1,  rpb_list_keys_req__number_ranges,
  (ProtobufCMessageInit) rpb_list_keys_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_keys_resp__field_descriptors[2] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbListKeysResp, n_keys),
    offsetof(RpbListKeysResp, keys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbListKeysResp, has_done),
    offsetof(RpbListKeysResp, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_keys_resp__field_indices_by_name[] = {
  1,   /* field[1] = done */
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange rpb_list_keys_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_list_keys_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListKeysResp",
  "RpbListKeysResp",
  "RpbListKeysResp",
  "",
  sizeof(RpbListKeysResp),
  2,
  rpb_list_keys_resp__field_descriptors,
  rpb_list_keys_resp__field_indices_by_name,
  1,  rpb_list_keys_resp__number_ranges,
  (ProtobufCMessageInit) rpb_list_keys_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_map_red_req__field_descriptors[2] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbMapRedReq, request),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbMapRedReq, content_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_map_red_req__field_indices_by_name[] = {
  1,   /* field[1] = content_type */
  0,   /* field[0] = request */
};
static const ProtobufCIntRange rpb_map_red_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_map_red_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbMapRedReq",
  "RpbMapRedReq",
  "RpbMapRedReq",
  "",
  sizeof(RpbMapRedReq),
  2,
  rpb_map_red_req__field_descriptors,
  rpb_map_red_req__field_indices_by_name,
  1,  rpb_map_red_req__number_ranges,
  (ProtobufCMessageInit) rpb_map_red_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_map_red_resp__field_descriptors[3] =
{
  {
    "phase",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbMapRedResp, has_phase),
    offsetof(RpbMapRedResp, phase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbMapRedResp, has_response),
    offsetof(RpbMapRedResp, response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbMapRedResp, has_done),
    offsetof(RpbMapRedResp, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_map_red_resp__field_indices_by_name[] = {
  2,   /* field[2] = done */
  0,   /* field[0] = phase */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange rpb_map_red_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_map_red_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbMapRedResp",
  "RpbMapRedResp",
  "RpbMapRedResp",
  "",
  sizeof(RpbMapRedResp),
  3,
  rpb_map_red_resp__field_descriptors,
  rpb_map_red_resp__field_indices_by_name,
  1,  rpb_map_red_resp__number_ranges,
  (ProtobufCMessageInit) rpb_map_red_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue rpb_index_req__index_query_type__enum_values_by_number[2] =
{
  { "eq", "RPB_INDEX_REQ__INDEX_QUERY_TYPE__eq", 0 },
  { "range", "RPB_INDEX_REQ__INDEX_QUERY_TYPE__range", 1 },
};
static const ProtobufCIntRange rpb_index_req__index_query_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex rpb_index_req__index_query_type__enum_values_by_name[2] =
{
  { "eq", 0 },
  { "range", 1 },
};
const ProtobufCEnumDescriptor rpb_index_req__index_query_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RpbIndexReq.IndexQueryType",
  "IndexQueryType",
  "RpbIndexReq__IndexQueryType",
  "",
  2,
  rpb_index_req__index_query_type__enum_values_by_number,
  2,
  rpb_index_req__index_query_type__enum_values_by_name,
  1,
  rpb_index_req__index_query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpb_index_req__field_descriptors[14] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbIndexReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbIndexReq, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qtype",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RpbIndexReq, qtype),
    &rpb_index_req__index_query_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_key),
    offsetof(RpbIndexReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_min",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_range_min),
    offsetof(RpbIndexReq, range_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_max",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_range_max),
    offsetof(RpbIndexReq, range_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_terms",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbIndexReq, has_return_terms),
    offsetof(RpbIndexReq, return_terms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbIndexReq, has_stream),
    offsetof(RpbIndexReq, stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_results",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbIndexReq, has_max_results),
    offsetof(RpbIndexReq, max_results),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "continuation",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_continuation),
    offsetof(RpbIndexReq, continuation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbIndexReq, has_timeout),
    offsetof(RpbIndexReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_type),
    offsetof(RpbIndexReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "term_regex",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexReq, has_term_regex),
    offsetof(RpbIndexReq, term_regex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pagination_sort",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbIndexReq, has_pagination_sort),
    offsetof(RpbIndexReq, pagination_sort),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_index_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  9,   /* field[9] = continuation */
  1,   /* field[1] = index */
  3,   /* field[3] = key */
  8,   /* field[8] = max_results */
  13,   /* field[13] = pagination_sort */
  2,   /* field[2] = qtype */
  5,   /* field[5] = range_max */
  4,   /* field[4] = range_min */
  6,   /* field[6] = return_terms */
  7,   /* field[7] = stream */
  12,   /* field[12] = term_regex */
  10,   /* field[10] = timeout */
  11,   /* field[11] = type */
};
static const ProtobufCIntRange rpb_index_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor rpb_index_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbIndexReq",
  "RpbIndexReq",
  "RpbIndexReq",
  "",
  sizeof(RpbIndexReq),
  14,
  rpb_index_req__field_descriptors,
  rpb_index_req__field_indices_by_name,
  1,  rpb_index_req__number_ranges,
  (ProtobufCMessageInit) rpb_index_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_index_resp__field_descriptors[4] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexResp, n_keys),
    offsetof(RpbIndexResp, keys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "results",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbIndexResp, n_results),
    offsetof(RpbIndexResp, results),
    &rpb_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "continuation",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbIndexResp, has_continuation),
    offsetof(RpbIndexResp, continuation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbIndexResp, has_done),
    offsetof(RpbIndexResp, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_index_resp__field_indices_by_name[] = {
  2,   /* field[2] = continuation */
  3,   /* field[3] = done */
  0,   /* field[0] = keys */
  1,   /* field[1] = results */
};
static const ProtobufCIntRange rpb_index_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpb_index_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbIndexResp",
  "RpbIndexResp",
  "RpbIndexResp",
  "",
  sizeof(RpbIndexResp),
  4,
  rpb_index_resp__field_descriptors,
  rpb_index_resp__field_indices_by_name,
  1,  rpb_index_resp__number_ranges,
  (ProtobufCMessageInit) rpb_index_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean rpb_csbucket_req__start_incl__default_value = 1;
static const protobuf_c_boolean rpb_csbucket_req__end_incl__default_value = 0;
static const ProtobufCFieldDescriptor rpb_csbucket_req__field_descriptors[9] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCSBucketReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCSBucketReq, start_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbCSBucketReq, has_end_key),
    offsetof(RpbCSBucketReq, end_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_incl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCSBucketReq, has_start_incl),
    offsetof(RpbCSBucketReq, start_incl),
    NULL,
    &rpb_csbucket_req__start_incl__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_incl",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCSBucketReq, has_end_incl),
    offsetof(RpbCSBucketReq, end_incl),
    NULL,
    &rpb_csbucket_req__end_incl__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "continuation",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbCSBucketReq, has_continuation),
    offsetof(RpbCSBucketReq, continuation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_results",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCSBucketReq, has_max_results),
    offsetof(RpbCSBucketReq, max_results),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCSBucketReq, has_timeout),
    offsetof(RpbCSBucketReq, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbCSBucketReq, has_type),
    offsetof(RpbCSBucketReq, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_csbucket_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  5,   /* field[5] = continuation */
  4,   /* field[4] = end_incl */
  2,   /* field[2] = end_key */
  6,   /* field[6] = max_results */
  3,   /* field[3] = start_incl */
  1,   /* field[1] = start_key */
  7,   /* field[7] = timeout */
  8,   /* field[8] = type */
};
static const ProtobufCIntRange rpb_csbucket_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rpb_csbucket_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCSBucketReq",
  "RpbCSBucketReq",
  "RpbCSBucketReq",
  "",
  sizeof(RpbCSBucketReq),
  9,
  rpb_csbucket_req__field_descriptors,
  rpb_csbucket_req__field_indices_by_name,
  1,  rpb_csbucket_req__number_ranges,
  (ProtobufCMessageInit) rpb_csbucket_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_csbucket_resp__field_descriptors[3] =
{
  {
    "objects",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbCSBucketResp, n_objects),
    offsetof(RpbCSBucketResp, objects),
    &rpb_index_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "continuation",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbCSBucketResp, has_continuation),
    offsetof(RpbCSBucketResp, continuation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCSBucketResp, has_done),
    offsetof(RpbCSBucketResp, done),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_csbucket_resp__field_indices_by_name[] = {
  1,   /* field[1] = continuation */
  2,   /* field[2] = done */
  0,   /* field[0] = objects */
};
static const ProtobufCIntRange rpb_csbucket_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_csbucket_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCSBucketResp",
  "RpbCSBucketResp",
  "RpbCSBucketResp",
  "",
  sizeof(RpbCSBucketResp),
  3,
  rpb_csbucket_resp__field_descriptors,
  rpb_csbucket_resp__field_indices_by_name,
  1,  rpb_csbucket_resp__number_ranges,
  (ProtobufCMessageInit) rpb_csbucket_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_index_object__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbIndexObject, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpbIndexObject, object),
    &rpb_get_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_index_object__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = object */
};
static const ProtobufCIntRange rpb_index_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_index_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbIndexObject",
  "RpbIndexObject",
  "RpbIndexObject",
  "",
  sizeof(RpbIndexObject),
  2,
  rpb_index_object__field_descriptors,
  rpb_index_object__field_indices_by_name,
  1,  rpb_index_object__number_ranges,
  (ProtobufCMessageInit) rpb_index_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_content__field_descriptors[11] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbContent, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbContent, has_content_type),
    offsetof(RpbContent, content_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "charset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbContent, has_charset),
    offsetof(RpbContent, charset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_encoding",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbContent, has_content_encoding),
    offsetof(RpbContent, content_encoding),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vtag",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbContent, has_vtag),
    offsetof(RpbContent, vtag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "links",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbContent, n_links),
    offsetof(RpbContent, links),
    &rpb_link__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_mod",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbContent, has_last_mod),
    offsetof(RpbContent, last_mod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_mod_usecs",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbContent, has_last_mod_usecs),
    offsetof(RpbContent, last_mod_usecs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usermeta",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbContent, n_usermeta),
    offsetof(RpbContent, usermeta),
    &rpb_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexes",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbContent, n_indexes),
    offsetof(RpbContent, indexes),
    &rpb_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbContent, has_deleted),
    offsetof(RpbContent, deleted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_content__field_indices_by_name[] = {
  2,   /* field[2] = charset */
  3,   /* field[3] = content_encoding */
  1,   /* field[1] = content_type */
  10,   /* field[10] = deleted */
  9,   /* field[9] = indexes */
  6,   /* field[6] = last_mod */
  7,   /* field[7] = last_mod_usecs */
  5,   /* field[5] = links */
  8,   /* field[8] = usermeta */
  0,   /* field[0] = value */
  4,   /* field[4] = vtag */
};
static const ProtobufCIntRange rpb_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor rpb_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbContent",
  "RpbContent",
  "RpbContent",
  "",
  sizeof(RpbContent),
  11,
  rpb_content__field_descriptors,
  rpb_content__field_indices_by_name,
  1,  rpb_content__number_ranges,
  (ProtobufCMessageInit) rpb_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_link__field_descriptors[3] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbLink, has_bucket),
    offsetof(RpbLink, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbLink, has_key),
    offsetof(RpbLink, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbLink, has_tag),
    offsetof(RpbLink, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_link__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  1,   /* field[1] = key */
  2,   /* field[2] = tag */
};
static const ProtobufCIntRange rpb_link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_link__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbLink",
  "RpbLink",
  "RpbLink",
  "",
  sizeof(RpbLink),
  3,
  rpb_link__field_descriptors,
  rpb_link__field_indices_by_name,
  1,  rpb_link__number_ranges,
  (ProtobufCMessageInit) rpb_link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_counter_update_req__field_descriptors[7] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCounterUpdateReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCounterUpdateReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(RpbCounterUpdateReq, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCounterUpdateReq, has_w),
    offsetof(RpbCounterUpdateReq, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCounterUpdateReq, has_dw),
    offsetof(RpbCounterUpdateReq, dw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCounterUpdateReq, has_pw),
    offsetof(RpbCounterUpdateReq, pw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "returnvalue",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCounterUpdateReq, has_returnvalue),
    offsetof(RpbCounterUpdateReq, returnvalue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_counter_update_req__field_indices_by_name[] = {
  2,   /* field[2] = amount */
  0,   /* field[0] = bucket */
  4,   /* field[4] = dw */
  1,   /* field[1] = key */
  5,   /* field[5] = pw */
  6,   /* field[6] = returnvalue */
  3,   /* field[3] = w */
};
static const ProtobufCIntRange rpb_counter_update_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor rpb_counter_update_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCounterUpdateReq",
  "RpbCounterUpdateReq",
  "RpbCounterUpdateReq",
  "",
  sizeof(RpbCounterUpdateReq),
  7,
  rpb_counter_update_req__field_descriptors,
  rpb_counter_update_req__field_indices_by_name,
  1,  rpb_counter_update_req__number_ranges,
  (ProtobufCMessageInit) rpb_counter_update_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_counter_update_resp__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(RpbCounterUpdateResp, has_value),
    offsetof(RpbCounterUpdateResp, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_counter_update_resp__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange rpb_counter_update_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_counter_update_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCounterUpdateResp",
  "RpbCounterUpdateResp",
  "RpbCounterUpdateResp",
  "",
  sizeof(RpbCounterUpdateResp),
  1,
  rpb_counter_update_resp__field_descriptors,
  rpb_counter_update_resp__field_indices_by_name,
  1,  rpb_counter_update_resp__number_ranges,
  (ProtobufCMessageInit) rpb_counter_update_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_counter_get_req__field_descriptors[6] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCounterGetReq, bucket),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbCounterGetReq, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCounterGetReq, has_r),
    offsetof(RpbCounterGetReq, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbCounterGetReq, has_pr),
    offsetof(RpbCounterGetReq, pr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basic_quorum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCounterGetReq, has_basic_quorum),
    offsetof(RpbCounterGetReq, basic_quorum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notfound_ok",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RpbCounterGetReq, has_notfound_ok),
    offsetof(RpbCounterGetReq, notfound_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_counter_get_req__field_indices_by_name[] = {
  4,   /* field[4] = basic_quorum */
  0,   /* field[0] = bucket */
  1,   /* field[1] = key */
  5,   /* field[5] = notfound_ok */
  3,   /* field[3] = pr */
  2,   /* field[2] = r */
};
static const ProtobufCIntRange rpb_counter_get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpb_counter_get_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCounterGetReq",
  "RpbCounterGetReq",
  "RpbCounterGetReq",
  "",
  sizeof(RpbCounterGetReq),
  6,
  rpb_counter_get_req__field_descriptors,
  rpb_counter_get_req__field_indices_by_name,
  1,  rpb_counter_get_req__number_ranges,
  (ProtobufCMessageInit) rpb_counter_get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_counter_get_resp__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(RpbCounterGetResp, has_value),
    offsetof(RpbCounterGetResp, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_counter_get_resp__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange rpb_counter_get_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_counter_get_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbCounterGetResp",
  "RpbCounterGetResp",
  "RpbCounterGetResp",
  "",
  sizeof(RpbCounterGetResp),
  1,
  rpb_counter_get_resp__field_descriptors,
  rpb_counter_get_resp__field_indices_by_name,
  1,  rpb_counter_get_resp__number_ranges,
  (ProtobufCMessageInit) rpb_counter_get_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
