/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: riak_search.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "riak_search.pb-c.h"
void   rpb_search_doc__init
                     (RpbSearchDoc         *message)
{
  static RpbSearchDoc init_value = RPB_SEARCH_DOC__INIT;
  *message = init_value;
}
size_t rpb_search_doc__get_packed_size
                     (const RpbSearchDoc *message)
{
  assert(message->base.descriptor == &rpb_search_doc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_search_doc__pack
                     (const RpbSearchDoc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_search_doc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_search_doc__pack_to_buffer
                     (const RpbSearchDoc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_search_doc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSearchDoc *
       rpb_search_doc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSearchDoc *)
     protobuf_c_message_unpack (&rpb_search_doc__descriptor,
                                allocator, len, data);
}
void   rpb_search_doc__free_unpacked
                     (RpbSearchDoc *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_search_doc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_search_query_req__init
                     (RpbSearchQueryReq         *message)
{
  static RpbSearchQueryReq init_value = RPB_SEARCH_QUERY_REQ__INIT;
  *message = init_value;
}
size_t rpb_search_query_req__get_packed_size
                     (const RpbSearchQueryReq *message)
{
  assert(message->base.descriptor == &rpb_search_query_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_search_query_req__pack
                     (const RpbSearchQueryReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_search_query_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_search_query_req__pack_to_buffer
                     (const RpbSearchQueryReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_search_query_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSearchQueryReq *
       rpb_search_query_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSearchQueryReq *)
     protobuf_c_message_unpack (&rpb_search_query_req__descriptor,
                                allocator, len, data);
}
void   rpb_search_query_req__free_unpacked
                     (RpbSearchQueryReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_search_query_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_search_query_resp__init
                     (RpbSearchQueryResp         *message)
{
  static RpbSearchQueryResp init_value = RPB_SEARCH_QUERY_RESP__INIT;
  *message = init_value;
}
size_t rpb_search_query_resp__get_packed_size
                     (const RpbSearchQueryResp *message)
{
  assert(message->base.descriptor == &rpb_search_query_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_search_query_resp__pack
                     (const RpbSearchQueryResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_search_query_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_search_query_resp__pack_to_buffer
                     (const RpbSearchQueryResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_search_query_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSearchQueryResp *
       rpb_search_query_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSearchQueryResp *)
     protobuf_c_message_unpack (&rpb_search_query_resp__descriptor,
                                allocator, len, data);
}
void   rpb_search_query_resp__free_unpacked
                     (RpbSearchQueryResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_search_query_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpb_search_doc__field_descriptors[1] =
{
  {
    "fields",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbSearchDoc, n_fields),
    offsetof(RpbSearchDoc, fields),
    &rpb_pair__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_search_doc__field_indices_by_name[] = {
  0,   /* field[0] = fields */
};
static const ProtobufCIntRange rpb_search_doc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_search_doc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSearchDoc",
  "RpbSearchDoc",
  "RpbSearchDoc",
  "",
  sizeof(RpbSearchDoc),
  1,
  rpb_search_doc__field_descriptors,
  rpb_search_doc__field_indices_by_name,
  1,  rpb_search_doc__number_ranges,
  (ProtobufCMessageInit) rpb_search_doc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_search_query_req__field_descriptors[10] =
{
  {
    "q",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbSearchQueryReq, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbSearchQueryReq, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbSearchQueryReq, has_rows),
    offsetof(RpbSearchQueryReq, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbSearchQueryReq, has_start),
    offsetof(RpbSearchQueryReq, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, has_sort),
    offsetof(RpbSearchQueryReq, sort),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, has_filter),
    offsetof(RpbSearchQueryReq, filter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "df",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, has_df),
    offsetof(RpbSearchQueryReq, df),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, has_op),
    offsetof(RpbSearchQueryReq, op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fl",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, n_fl),
    offsetof(RpbSearchQueryReq, fl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "presort",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbSearchQueryReq, has_presort),
    offsetof(RpbSearchQueryReq, presort),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_search_query_req__field_indices_by_name[] = {
  6,   /* field[6] = df */
  5,   /* field[5] = filter */
  8,   /* field[8] = fl */
  1,   /* field[1] = index */
  7,   /* field[7] = op */
  9,   /* field[9] = presort */
  0,   /* field[0] = q */
  2,   /* field[2] = rows */
  4,   /* field[4] = sort */
  3,   /* field[3] = start */
};
static const ProtobufCIntRange rpb_search_query_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor rpb_search_query_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSearchQueryReq",
  "RpbSearchQueryReq",
  "RpbSearchQueryReq",
  "",
  sizeof(RpbSearchQueryReq),
  10,
  rpb_search_query_req__field_descriptors,
  rpb_search_query_req__field_indices_by_name,
  1,  rpb_search_query_req__number_ranges,
  (ProtobufCMessageInit) rpb_search_query_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_search_query_resp__field_descriptors[3] =
{
  {
    "docs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbSearchQueryResp, n_docs),
    offsetof(RpbSearchQueryResp, docs),
    &rpb_search_doc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_score",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RpbSearchQueryResp, has_max_score),
    offsetof(RpbSearchQueryResp, max_score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_found",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbSearchQueryResp, has_num_found),
    offsetof(RpbSearchQueryResp, num_found),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_search_query_resp__field_indices_by_name[] = {
  0,   /* field[0] = docs */
  1,   /* field[1] = max_score */
  2,   /* field[2] = num_found */
};
static const ProtobufCIntRange rpb_search_query_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_search_query_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSearchQueryResp",
  "RpbSearchQueryResp",
  "RpbSearchQueryResp",
  "",
  sizeof(RpbSearchQueryResp),
  3,
  rpb_search_query_resp__field_descriptors,
  rpb_search_query_resp__field_indices_by_name,
  1,  rpb_search_query_resp__number_ranges,
  (ProtobufCMessageInit) rpb_search_query_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
