/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: riak_yokozuna.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "riak_yokozuna.pb-c.h"
void   rpb_yokozuna_index__init
                     (RpbYokozunaIndex         *message)
{
  static RpbYokozunaIndex init_value = RPB_YOKOZUNA_INDEX__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_index__get_packed_size
                     (const RpbYokozunaIndex *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_index__pack
                     (const RpbYokozunaIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_index__pack_to_buffer
                     (const RpbYokozunaIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaIndex *
       rpb_yokozuna_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaIndex *)
     protobuf_c_message_unpack (&rpb_yokozuna_index__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_index__free_unpacked
                     (RpbYokozunaIndex *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_index_get_req__init
                     (RpbYokozunaIndexGetReq         *message)
{
  static RpbYokozunaIndexGetReq init_value = RPB_YOKOZUNA_INDEX_GET_REQ__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_index_get_req__get_packed_size
                     (const RpbYokozunaIndexGetReq *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_index_get_req__pack
                     (const RpbYokozunaIndexGetReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_index_get_req__pack_to_buffer
                     (const RpbYokozunaIndexGetReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaIndexGetReq *
       rpb_yokozuna_index_get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaIndexGetReq *)
     protobuf_c_message_unpack (&rpb_yokozuna_index_get_req__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_index_get_req__free_unpacked
                     (RpbYokozunaIndexGetReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_index_get_resp__init
                     (RpbYokozunaIndexGetResp         *message)
{
  static RpbYokozunaIndexGetResp init_value = RPB_YOKOZUNA_INDEX_GET_RESP__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_index_get_resp__get_packed_size
                     (const RpbYokozunaIndexGetResp *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_index_get_resp__pack
                     (const RpbYokozunaIndexGetResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_index_get_resp__pack_to_buffer
                     (const RpbYokozunaIndexGetResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaIndexGetResp *
       rpb_yokozuna_index_get_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaIndexGetResp *)
     protobuf_c_message_unpack (&rpb_yokozuna_index_get_resp__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_index_get_resp__free_unpacked
                     (RpbYokozunaIndexGetResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_get_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_index_put_req__init
                     (RpbYokozunaIndexPutReq         *message)
{
  static RpbYokozunaIndexPutReq init_value = RPB_YOKOZUNA_INDEX_PUT_REQ__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_index_put_req__get_packed_size
                     (const RpbYokozunaIndexPutReq *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_put_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_index_put_req__pack
                     (const RpbYokozunaIndexPutReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_put_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_index_put_req__pack_to_buffer
                     (const RpbYokozunaIndexPutReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_put_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaIndexPutReq *
       rpb_yokozuna_index_put_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaIndexPutReq *)
     protobuf_c_message_unpack (&rpb_yokozuna_index_put_req__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_index_put_req__free_unpacked
                     (RpbYokozunaIndexPutReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_put_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_index_delete_req__init
                     (RpbYokozunaIndexDeleteReq         *message)
{
  static RpbYokozunaIndexDeleteReq init_value = RPB_YOKOZUNA_INDEX_DELETE_REQ__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_index_delete_req__get_packed_size
                     (const RpbYokozunaIndexDeleteReq *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_delete_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_index_delete_req__pack
                     (const RpbYokozunaIndexDeleteReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_delete_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_index_delete_req__pack_to_buffer
                     (const RpbYokozunaIndexDeleteReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_delete_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaIndexDeleteReq *
       rpb_yokozuna_index_delete_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaIndexDeleteReq *)
     protobuf_c_message_unpack (&rpb_yokozuna_index_delete_req__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_index_delete_req__free_unpacked
                     (RpbYokozunaIndexDeleteReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_index_delete_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_schema__init
                     (RpbYokozunaSchema         *message)
{
  static RpbYokozunaSchema init_value = RPB_YOKOZUNA_SCHEMA__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_schema__get_packed_size
                     (const RpbYokozunaSchema *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_schema__pack
                     (const RpbYokozunaSchema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_schema__pack_to_buffer
                     (const RpbYokozunaSchema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaSchema *
       rpb_yokozuna_schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaSchema *)
     protobuf_c_message_unpack (&rpb_yokozuna_schema__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_schema__free_unpacked
                     (RpbYokozunaSchema *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_schema_put_req__init
                     (RpbYokozunaSchemaPutReq         *message)
{
  static RpbYokozunaSchemaPutReq init_value = RPB_YOKOZUNA_SCHEMA_PUT_REQ__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_schema_put_req__get_packed_size
                     (const RpbYokozunaSchemaPutReq *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_put_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_schema_put_req__pack
                     (const RpbYokozunaSchemaPutReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_put_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_schema_put_req__pack_to_buffer
                     (const RpbYokozunaSchemaPutReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_put_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaSchemaPutReq *
       rpb_yokozuna_schema_put_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaSchemaPutReq *)
     protobuf_c_message_unpack (&rpb_yokozuna_schema_put_req__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_schema_put_req__free_unpacked
                     (RpbYokozunaSchemaPutReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_put_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_schema_get_req__init
                     (RpbYokozunaSchemaGetReq         *message)
{
  static RpbYokozunaSchemaGetReq init_value = RPB_YOKOZUNA_SCHEMA_GET_REQ__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_schema_get_req__get_packed_size
                     (const RpbYokozunaSchemaGetReq *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_schema_get_req__pack
                     (const RpbYokozunaSchemaGetReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_schema_get_req__pack_to_buffer
                     (const RpbYokozunaSchemaGetReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaSchemaGetReq *
       rpb_yokozuna_schema_get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaSchemaGetReq *)
     protobuf_c_message_unpack (&rpb_yokozuna_schema_get_req__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_schema_get_req__free_unpacked
                     (RpbYokozunaSchemaGetReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_yokozuna_schema_get_resp__init
                     (RpbYokozunaSchemaGetResp         *message)
{
  static RpbYokozunaSchemaGetResp init_value = RPB_YOKOZUNA_SCHEMA_GET_RESP__INIT;
  *message = init_value;
}
size_t rpb_yokozuna_schema_get_resp__get_packed_size
                     (const RpbYokozunaSchemaGetResp *message)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_yokozuna_schema_get_resp__pack
                     (const RpbYokozunaSchemaGetResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_yokozuna_schema_get_resp__pack_to_buffer
                     (const RpbYokozunaSchemaGetResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbYokozunaSchemaGetResp *
       rpb_yokozuna_schema_get_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbYokozunaSchemaGetResp *)
     protobuf_c_message_unpack (&rpb_yokozuna_schema_get_resp__descriptor,
                                allocator, len, data);
}
void   rpb_yokozuna_schema_get_resp__free_unpacked
                     (RpbYokozunaSchemaGetResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rpb_yokozuna_schema_get_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpb_yokozuna_index__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaIndex, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbYokozunaIndex, has_schema),
    offsetof(RpbYokozunaIndex, schema),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RpbYokozunaIndex, has_n_val),
    offsetof(RpbYokozunaIndex, n_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_index__field_indices_by_name[] = {
  2,   /* field[2] = n_val */
  0,   /* field[0] = name */
  1,   /* field[1] = schema */
};
static const ProtobufCIntRange rpb_yokozuna_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaIndex",
  "RpbYokozunaIndex",
  "RpbYokozunaIndex",
  "",
  sizeof(RpbYokozunaIndex),
  3,
  rpb_yokozuna_index__field_descriptors,
  rpb_yokozuna_index__field_indices_by_name,
  1,  rpb_yokozuna_index__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_index_get_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbYokozunaIndexGetReq, has_name),
    offsetof(RpbYokozunaIndexGetReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_index_get_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange rpb_yokozuna_index_get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_index_get_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaIndexGetReq",
  "RpbYokozunaIndexGetReq",
  "RpbYokozunaIndexGetReq",
  "",
  sizeof(RpbYokozunaIndexGetReq),
  1,
  rpb_yokozuna_index_get_req__field_descriptors,
  rpb_yokozuna_index_get_req__field_indices_by_name,
  1,  rpb_yokozuna_index_get_req__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_index_get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_index_get_resp__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RpbYokozunaIndexGetResp, n_index),
    offsetof(RpbYokozunaIndexGetResp, index),
    &rpb_yokozuna_index__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_index_get_resp__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange rpb_yokozuna_index_get_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_index_get_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaIndexGetResp",
  "RpbYokozunaIndexGetResp",
  "RpbYokozunaIndexGetResp",
  "",
  sizeof(RpbYokozunaIndexGetResp),
  1,
  rpb_yokozuna_index_get_resp__field_descriptors,
  rpb_yokozuna_index_get_resp__field_indices_by_name,
  1,  rpb_yokozuna_index_get_resp__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_index_get_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_index_put_req__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaIndexPutReq, index),
    &rpb_yokozuna_index__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_index_put_req__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange rpb_yokozuna_index_put_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_index_put_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaIndexPutReq",
  "RpbYokozunaIndexPutReq",
  "RpbYokozunaIndexPutReq",
  "",
  sizeof(RpbYokozunaIndexPutReq),
  1,
  rpb_yokozuna_index_put_req__field_descriptors,
  rpb_yokozuna_index_put_req__field_indices_by_name,
  1,  rpb_yokozuna_index_put_req__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_index_put_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_index_delete_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaIndexDeleteReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_index_delete_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange rpb_yokozuna_index_delete_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_index_delete_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaIndexDeleteReq",
  "RpbYokozunaIndexDeleteReq",
  "RpbYokozunaIndexDeleteReq",
  "",
  sizeof(RpbYokozunaIndexDeleteReq),
  1,
  rpb_yokozuna_index_delete_req__field_descriptors,
  rpb_yokozuna_index_delete_req__field_indices_by_name,
  1,  rpb_yokozuna_index_delete_req__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_index_delete_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_schema__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaSchema, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(RpbYokozunaSchema, has_content),
    offsetof(RpbYokozunaSchema, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_schema__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange rpb_yokozuna_schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaSchema",
  "RpbYokozunaSchema",
  "RpbYokozunaSchema",
  "",
  sizeof(RpbYokozunaSchema),
  2,
  rpb_yokozuna_schema__field_descriptors,
  rpb_yokozuna_schema__field_indices_by_name,
  1,  rpb_yokozuna_schema__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_schema_put_req__field_descriptors[1] =
{
  {
    "schema",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaSchemaPutReq, schema),
    &rpb_yokozuna_schema__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_schema_put_req__field_indices_by_name[] = {
  0,   /* field[0] = schema */
};
static const ProtobufCIntRange rpb_yokozuna_schema_put_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_schema_put_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaSchemaPutReq",
  "RpbYokozunaSchemaPutReq",
  "RpbYokozunaSchemaPutReq",
  "",
  sizeof(RpbYokozunaSchemaPutReq),
  1,
  rpb_yokozuna_schema_put_req__field_descriptors,
  rpb_yokozuna_schema_put_req__field_indices_by_name,
  1,  rpb_yokozuna_schema_put_req__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_schema_put_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_schema_get_req__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaSchemaGetReq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_schema_get_req__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange rpb_yokozuna_schema_get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_schema_get_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaSchemaGetReq",
  "RpbYokozunaSchemaGetReq",
  "RpbYokozunaSchemaGetReq",
  "",
  sizeof(RpbYokozunaSchemaGetReq),
  1,
  rpb_yokozuna_schema_get_req__field_descriptors,
  rpb_yokozuna_schema_get_req__field_indices_by_name,
  1,  rpb_yokozuna_schema_get_req__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_schema_get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_yokozuna_schema_get_resp__field_descriptors[1] =
{
  {
    "schema",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RpbYokozunaSchemaGetResp, schema),
    &rpb_yokozuna_schema__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_yokozuna_schema_get_resp__field_indices_by_name[] = {
  0,   /* field[0] = schema */
};
static const ProtobufCIntRange rpb_yokozuna_schema_get_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_yokozuna_schema_get_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpbYokozunaSchemaGetResp",
  "RpbYokozunaSchemaGetResp",
  "RpbYokozunaSchemaGetResp",
  "",
  sizeof(RpbYokozunaSchemaGetResp),
  1,
  rpb_yokozuna_schema_get_resp__field_descriptors,
  rpb_yokozuna_schema_get_resp__field_indices_by_name,
  1,  rpb_yokozuna_schema_get_resp__number_ranges,
  (ProtobufCMessageInit) rpb_yokozuna_schema_get_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
