/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "riak.pb-c.h"
void   rpb_error_resp__init
                     (RpbErrorResp         *message)
{
  static RpbErrorResp init_value = RPB_ERROR_RESP__INIT;
  *message = init_value;
}
size_t rpb_error_resp__get_packed_size
                     (const RpbErrorResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_error_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_error_resp__pack
                     (const RpbErrorResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_error_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_error_resp__pack_to_buffer
                     (const RpbErrorResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_error_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbErrorResp *
       rpb_error_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbErrorResp *)
     protobuf_c_message_unpack (&rpb_error_resp__descriptor,
                                allocator, len, data);
}
void   rpb_error_resp__free_unpacked
                     (RpbErrorResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_error_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_server_info_resp__init
                     (RpbGetServerInfoResp         *message)
{
  static RpbGetServerInfoResp init_value = RPB_GET_SERVER_INFO_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_server_info_resp__get_packed_size
                     (const RpbGetServerInfoResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_server_info_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_server_info_resp__pack
                     (const RpbGetServerInfoResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_server_info_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_server_info_resp__pack_to_buffer
                     (const RpbGetServerInfoResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_server_info_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetServerInfoResp *
       rpb_get_server_info_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetServerInfoResp *)
     protobuf_c_message_unpack (&rpb_get_server_info_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_server_info_resp__free_unpacked
                     (RpbGetServerInfoResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_server_info_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_pair__init
                     (RpbPair         *message)
{
  static RpbPair init_value = RPB_PAIR__INIT;
  *message = init_value;
}
size_t rpb_pair__get_packed_size
                     (const RpbPair *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_pair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_pair__pack
                     (const RpbPair *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_pair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_pair__pack_to_buffer
                     (const RpbPair *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_pair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbPair *
       rpb_pair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbPair *)
     protobuf_c_message_unpack (&rpb_pair__descriptor,
                                allocator, len, data);
}
void   rpb_pair__free_unpacked
                     (RpbPair *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_pair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpb_error_resp__field_descriptors[2] =
{
  {
    "errmsg",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbErrorResp, errmsg),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errcode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbErrorResp, errcode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_error_resp__field_indices_by_name[] = {
  1,   /* field[1] = errcode */
  0,   /* field[0] = errmsg */
};
static const ProtobufCIntRange rpb_error_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_error_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbErrorResp",
  "RpbErrorResp",
  "RpbErrorResp",
  "",
  sizeof(RpbErrorResp),
  2,
  rpb_error_resp__field_descriptors,
  rpb_error_resp__field_indices_by_name,
  1,  rpb_error_resp__number_ranges,
  (ProtobufCMessageInit) rpb_error_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_server_info_resp__field_descriptors[2] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbGetServerInfoResp, has_node),
    PROTOBUF_C_OFFSETOF(RpbGetServerInfoResp, node),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbGetServerInfoResp, has_server_version),
    PROTOBUF_C_OFFSETOF(RpbGetServerInfoResp, server_version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_server_info_resp__field_indices_by_name[] = {
  0,   /* field[0] = node */
  1,   /* field[1] = server_version */
};
static const ProtobufCIntRange rpb_get_server_info_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_get_server_info_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetServerInfoResp",
  "RpbGetServerInfoResp",
  "RpbGetServerInfoResp",
  "",
  sizeof(RpbGetServerInfoResp),
  2,
  rpb_get_server_info_resp__field_descriptors,
  rpb_get_server_info_resp__field_indices_by_name,
  1,  rpb_get_server_info_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_server_info_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbPair, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbPair, has_value),
    PROTOBUF_C_OFFSETOF(RpbPair, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange rpb_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_pair__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbPair",
  "RpbPair",
  "RpbPair",
  "",
  sizeof(RpbPair),
  2,
  rpb_pair__field_descriptors,
  rpb_pair__field_indices_by_name,
  1,  rpb_pair__number_ranges,
  (ProtobufCMessageInit) rpb_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
