/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "riak_kv.pb-c.h"
void   rpb_get_client_id_resp__init
                     (RpbGetClientIdResp         *message)
{
  static RpbGetClientIdResp init_value = RPB_GET_CLIENT_ID_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_client_id_resp__get_packed_size
                     (const RpbGetClientIdResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_client_id_resp__pack
                     (const RpbGetClientIdResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_client_id_resp__pack_to_buffer
                     (const RpbGetClientIdResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetClientIdResp *
       rpb_get_client_id_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetClientIdResp *)
     protobuf_c_message_unpack (&rpb_get_client_id_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_client_id_resp__free_unpacked
                     (RpbGetClientIdResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_client_id_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_set_client_id_req__init
                     (RpbSetClientIdReq         *message)
{
  static RpbSetClientIdReq init_value = RPB_SET_CLIENT_ID_REQ__INIT;
  *message = init_value;
}
size_t rpb_set_client_id_req__get_packed_size
                     (const RpbSetClientIdReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_set_client_id_req__pack
                     (const RpbSetClientIdReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_set_client_id_req__pack_to_buffer
                     (const RpbSetClientIdReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_client_id_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSetClientIdReq *
       rpb_set_client_id_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSetClientIdReq *)
     protobuf_c_message_unpack (&rpb_set_client_id_req__descriptor,
                                allocator, len, data);
}
void   rpb_set_client_id_req__free_unpacked
                     (RpbSetClientIdReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_client_id_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_req__init
                     (RpbGetReq         *message)
{
  static RpbGetReq init_value = RPB_GET_REQ__INIT;
  *message = init_value;
}
size_t rpb_get_req__get_packed_size
                     (const RpbGetReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_req__pack
                     (const RpbGetReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_req__pack_to_buffer
                     (const RpbGetReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetReq *
       rpb_get_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetReq *)
     protobuf_c_message_unpack (&rpb_get_req__descriptor,
                                allocator, len, data);
}
void   rpb_get_req__free_unpacked
                     (RpbGetReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_resp__init
                     (RpbGetResp         *message)
{
  static RpbGetResp init_value = RPB_GET_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_resp__get_packed_size
                     (const RpbGetResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_resp__pack
                     (const RpbGetResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_resp__pack_to_buffer
                     (const RpbGetResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetResp *
       rpb_get_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetResp *)
     protobuf_c_message_unpack (&rpb_get_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_resp__free_unpacked
                     (RpbGetResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_put_req__init
                     (RpbPutReq         *message)
{
  static RpbPutReq init_value = RPB_PUT_REQ__INIT;
  *message = init_value;
}
size_t rpb_put_req__get_packed_size
                     (const RpbPutReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_put_req__pack
                     (const RpbPutReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_put_req__pack_to_buffer
                     (const RpbPutReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbPutReq *
       rpb_put_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbPutReq *)
     protobuf_c_message_unpack (&rpb_put_req__descriptor,
                                allocator, len, data);
}
void   rpb_put_req__free_unpacked
                     (RpbPutReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_put_resp__init
                     (RpbPutResp         *message)
{
  static RpbPutResp init_value = RPB_PUT_RESP__INIT;
  *message = init_value;
}
size_t rpb_put_resp__get_packed_size
                     (const RpbPutResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_put_resp__pack
                     (const RpbPutResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_put_resp__pack_to_buffer
                     (const RpbPutResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbPutResp *
       rpb_put_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbPutResp *)
     protobuf_c_message_unpack (&rpb_put_resp__descriptor,
                                allocator, len, data);
}
void   rpb_put_resp__free_unpacked
                     (RpbPutResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_put_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_del_req__init
                     (RpbDelReq         *message)
{
  static RpbDelReq init_value = RPB_DEL_REQ__INIT;
  *message = init_value;
}
size_t rpb_del_req__get_packed_size
                     (const RpbDelReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_del_req__pack
                     (const RpbDelReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_del_req__pack_to_buffer
                     (const RpbDelReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_del_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbDelReq *
       rpb_del_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbDelReq *)
     protobuf_c_message_unpack (&rpb_del_req__descriptor,
                                allocator, len, data);
}
void   rpb_del_req__free_unpacked
                     (RpbDelReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_del_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_buckets_resp__init
                     (RpbListBucketsResp         *message)
{
  static RpbListBucketsResp init_value = RPB_LIST_BUCKETS_RESP__INIT;
  *message = init_value;
}
size_t rpb_list_buckets_resp__get_packed_size
                     (const RpbListBucketsResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_buckets_resp__pack
                     (const RpbListBucketsResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_buckets_resp__pack_to_buffer
                     (const RpbListBucketsResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListBucketsResp *
       rpb_list_buckets_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListBucketsResp *)
     protobuf_c_message_unpack (&rpb_list_buckets_resp__descriptor,
                                allocator, len, data);
}
void   rpb_list_buckets_resp__free_unpacked
                     (RpbListBucketsResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_buckets_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_keys_req__init
                     (RpbListKeysReq         *message)
{
  static RpbListKeysReq init_value = RPB_LIST_KEYS_REQ__INIT;
  *message = init_value;
}
size_t rpb_list_keys_req__get_packed_size
                     (const RpbListKeysReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_keys_req__pack
                     (const RpbListKeysReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_keys_req__pack_to_buffer
                     (const RpbListKeysReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListKeysReq *
       rpb_list_keys_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListKeysReq *)
     protobuf_c_message_unpack (&rpb_list_keys_req__descriptor,
                                allocator, len, data);
}
void   rpb_list_keys_req__free_unpacked
                     (RpbListKeysReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_list_keys_resp__init
                     (RpbListKeysResp         *message)
{
  static RpbListKeysResp init_value = RPB_LIST_KEYS_RESP__INIT;
  *message = init_value;
}
size_t rpb_list_keys_resp__get_packed_size
                     (const RpbListKeysResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_list_keys_resp__pack
                     (const RpbListKeysResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_list_keys_resp__pack_to_buffer
                     (const RpbListKeysResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbListKeysResp *
       rpb_list_keys_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbListKeysResp *)
     protobuf_c_message_unpack (&rpb_list_keys_resp__descriptor,
                                allocator, len, data);
}
void   rpb_list_keys_resp__free_unpacked
                     (RpbListKeysResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_list_keys_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_bucket_req__init
                     (RpbGetBucketReq         *message)
{
  static RpbGetBucketReq init_value = RPB_GET_BUCKET_REQ__INIT;
  *message = init_value;
}
size_t rpb_get_bucket_req__get_packed_size
                     (const RpbGetBucketReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_bucket_req__pack
                     (const RpbGetBucketReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_bucket_req__pack_to_buffer
                     (const RpbGetBucketReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetBucketReq *
       rpb_get_bucket_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetBucketReq *)
     protobuf_c_message_unpack (&rpb_get_bucket_req__descriptor,
                                allocator, len, data);
}
void   rpb_get_bucket_req__free_unpacked
                     (RpbGetBucketReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_get_bucket_resp__init
                     (RpbGetBucketResp         *message)
{
  static RpbGetBucketResp init_value = RPB_GET_BUCKET_RESP__INIT;
  *message = init_value;
}
size_t rpb_get_bucket_resp__get_packed_size
                     (const RpbGetBucketResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_get_bucket_resp__pack
                     (const RpbGetBucketResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_get_bucket_resp__pack_to_buffer
                     (const RpbGetBucketResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbGetBucketResp *
       rpb_get_bucket_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbGetBucketResp *)
     protobuf_c_message_unpack (&rpb_get_bucket_resp__descriptor,
                                allocator, len, data);
}
void   rpb_get_bucket_resp__free_unpacked
                     (RpbGetBucketResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_get_bucket_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_set_bucket_req__init
                     (RpbSetBucketReq         *message)
{
  static RpbSetBucketReq init_value = RPB_SET_BUCKET_REQ__INIT;
  *message = init_value;
}
size_t rpb_set_bucket_req__get_packed_size
                     (const RpbSetBucketReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_bucket_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_set_bucket_req__pack
                     (const RpbSetBucketReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_bucket_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_set_bucket_req__pack_to_buffer
                     (const RpbSetBucketReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_bucket_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbSetBucketReq *
       rpb_set_bucket_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbSetBucketReq *)
     protobuf_c_message_unpack (&rpb_set_bucket_req__descriptor,
                                allocator, len, data);
}
void   rpb_set_bucket_req__free_unpacked
                     (RpbSetBucketReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_set_bucket_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_map_red_req__init
                     (RpbMapRedReq         *message)
{
  static RpbMapRedReq init_value = RPB_MAP_RED_REQ__INIT;
  *message = init_value;
}
size_t rpb_map_red_req__get_packed_size
                     (const RpbMapRedReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_map_red_req__pack
                     (const RpbMapRedReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_map_red_req__pack_to_buffer
                     (const RpbMapRedReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbMapRedReq *
       rpb_map_red_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbMapRedReq *)
     protobuf_c_message_unpack (&rpb_map_red_req__descriptor,
                                allocator, len, data);
}
void   rpb_map_red_req__free_unpacked
                     (RpbMapRedReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_map_red_resp__init
                     (RpbMapRedResp         *message)
{
  static RpbMapRedResp init_value = RPB_MAP_RED_RESP__INIT;
  *message = init_value;
}
size_t rpb_map_red_resp__get_packed_size
                     (const RpbMapRedResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_map_red_resp__pack
                     (const RpbMapRedResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_map_red_resp__pack_to_buffer
                     (const RpbMapRedResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbMapRedResp *
       rpb_map_red_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbMapRedResp *)
     protobuf_c_message_unpack (&rpb_map_red_resp__descriptor,
                                allocator, len, data);
}
void   rpb_map_red_resp__free_unpacked
                     (RpbMapRedResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_map_red_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_index_req__init
                     (RpbIndexReq         *message)
{
  static RpbIndexReq init_value = RPB_INDEX_REQ__INIT;
  *message = init_value;
}
size_t rpb_index_req__get_packed_size
                     (const RpbIndexReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_index_req__pack
                     (const RpbIndexReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_index_req__pack_to_buffer
                     (const RpbIndexReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbIndexReq *
       rpb_index_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbIndexReq *)
     protobuf_c_message_unpack (&rpb_index_req__descriptor,
                                allocator, len, data);
}
void   rpb_index_req__free_unpacked
                     (RpbIndexReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_index_resp__init
                     (RpbIndexResp         *message)
{
  static RpbIndexResp init_value = RPB_INDEX_RESP__INIT;
  *message = init_value;
}
size_t rpb_index_resp__get_packed_size
                     (const RpbIndexResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_index_resp__pack
                     (const RpbIndexResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_index_resp__pack_to_buffer
                     (const RpbIndexResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbIndexResp *
       rpb_index_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbIndexResp *)
     protobuf_c_message_unpack (&rpb_index_resp__descriptor,
                                allocator, len, data);
}
void   rpb_index_resp__free_unpacked
                     (RpbIndexResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_index_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_content__init
                     (RpbContent         *message)
{
  static RpbContent init_value = RPB_CONTENT__INIT;
  *message = init_value;
}
size_t rpb_content__get_packed_size
                     (const RpbContent *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_content__pack
                     (const RpbContent *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_content__pack_to_buffer
                     (const RpbContent *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbContent *
       rpb_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbContent *)
     protobuf_c_message_unpack (&rpb_content__descriptor,
                                allocator, len, data);
}
void   rpb_content__free_unpacked
                     (RpbContent *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_link__init
                     (RpbLink         *message)
{
  static RpbLink init_value = RPB_LINK__INIT;
  *message = init_value;
}
size_t rpb_link__get_packed_size
                     (const RpbLink *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_link__pack
                     (const RpbLink *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_link__pack_to_buffer
                     (const RpbLink *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_link__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbLink *
       rpb_link__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbLink *)
     protobuf_c_message_unpack (&rpb_link__descriptor,
                                allocator, len, data);
}
void   rpb_link__free_unpacked
                     (RpbLink *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_link__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpb_bucket_props__init
                     (RpbBucketProps         *message)
{
  static RpbBucketProps init_value = RPB_BUCKET_PROPS__INIT;
  *message = init_value;
}
size_t rpb_bucket_props__get_packed_size
                     (const RpbBucketProps *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_bucket_props__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpb_bucket_props__pack
                     (const RpbBucketProps *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_bucket_props__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpb_bucket_props__pack_to_buffer
                     (const RpbBucketProps *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_bucket_props__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpbBucketProps *
       rpb_bucket_props__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpbBucketProps *)
     protobuf_c_message_unpack (&rpb_bucket_props__descriptor,
                                allocator, len, data);
}
void   rpb_bucket_props__free_unpacked
                     (RpbBucketProps *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpb_bucket_props__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpb_get_client_id_resp__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbGetClientIdResp, client_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_client_id_resp__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange rpb_get_client_id_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_get_client_id_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetClientIdResp",
  "RpbGetClientIdResp",
  "RpbGetClientIdResp",
  "",
  sizeof(RpbGetClientIdResp),
  1,
  rpb_get_client_id_resp__field_descriptors,
  rpb_get_client_id_resp__field_indices_by_name,
  1,  rpb_get_client_id_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_client_id_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_set_client_id_req__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbSetClientIdReq, client_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_set_client_id_req__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange rpb_set_client_id_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_set_client_id_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSetClientIdReq",
  "RpbSetClientIdReq",
  "RpbSetClientIdReq",
  "",
  sizeof(RpbSetClientIdReq),
  1,
  rpb_set_client_id_req__field_descriptors,
  rpb_set_client_id_req__field_indices_by_name,
  1,  rpb_set_client_id_req__number_ranges,
  (ProtobufCMessageInit) rpb_set_client_id_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_req__field_descriptors[9] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbGetReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbGetReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_r),
    PROTOBUF_C_OFFSETOF(RpbGetReq, r),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_pr),
    PROTOBUF_C_OFFSETOF(RpbGetReq, pr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basic_quorum",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_basic_quorum),
    PROTOBUF_C_OFFSETOF(RpbGetReq, basic_quorum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notfound_ok",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_notfound_ok),
    PROTOBUF_C_OFFSETOF(RpbGetReq, notfound_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_modified",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_if_modified),
    PROTOBUF_C_OFFSETOF(RpbGetReq, if_modified),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "head",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_head),
    PROTOBUF_C_OFFSETOF(RpbGetReq, head),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deletedvclock",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbGetReq, has_deletedvclock),
    PROTOBUF_C_OFFSETOF(RpbGetReq, deletedvclock),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_req__field_indices_by_name[] = {
  4,   /* field[4] = basic_quorum */
  0,   /* field[0] = bucket */
  8,   /* field[8] = deletedvclock */
  7,   /* field[7] = head */
  6,   /* field[6] = if_modified */
  1,   /* field[1] = key */
  5,   /* field[5] = notfound_ok */
  3,   /* field[3] = pr */
  2,   /* field[2] = r */
};
static const ProtobufCIntRange rpb_get_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rpb_get_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetReq",
  "RpbGetReq",
  "RpbGetReq",
  "",
  sizeof(RpbGetReq),
  9,
  rpb_get_req__field_descriptors,
  rpb_get_req__field_indices_by_name,
  1,  rpb_get_req__number_ranges,
  (ProtobufCMessageInit) rpb_get_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_resp__field_descriptors[3] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RpbGetResp, n_content),
    PROTOBUF_C_OFFSETOF(RpbGetResp, content),
    &rpb_content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbGetResp, has_vclock),
    PROTOBUF_C_OFFSETOF(RpbGetResp, vclock),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unchanged",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbGetResp, has_unchanged),
    PROTOBUF_C_OFFSETOF(RpbGetResp, unchanged),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_resp__field_indices_by_name[] = {
  0,   /* field[0] = content */
  2,   /* field[2] = unchanged */
  1,   /* field[1] = vclock */
};
static const ProtobufCIntRange rpb_get_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_get_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetResp",
  "RpbGetResp",
  "RpbGetResp",
  "",
  sizeof(RpbGetResp),
  3,
  rpb_get_resp__field_descriptors,
  rpb_get_resp__field_indices_by_name,
  1,  rpb_get_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_put_req__field_descriptors[11] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbPutReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_key),
    PROTOBUF_C_OFFSETOF(RpbPutReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_vclock),
    PROTOBUF_C_OFFSETOF(RpbPutReq, vclock),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbPutReq, content),
    &rpb_content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_w),
    PROTOBUF_C_OFFSETOF(RpbPutReq, w),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_dw),
    PROTOBUF_C_OFFSETOF(RpbPutReq, dw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_body",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_return_body),
    PROTOBUF_C_OFFSETOF(RpbPutReq, return_body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_pw),
    PROTOBUF_C_OFFSETOF(RpbPutReq, pw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_not_modified",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_if_not_modified),
    PROTOBUF_C_OFFSETOF(RpbPutReq, if_not_modified),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_none_match",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_if_none_match),
    PROTOBUF_C_OFFSETOF(RpbPutReq, if_none_match),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_head",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbPutReq, has_return_head),
    PROTOBUF_C_OFFSETOF(RpbPutReq, return_head),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_put_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  3,   /* field[3] = content */
  5,   /* field[5] = dw */
  9,   /* field[9] = if_none_match */
  8,   /* field[8] = if_not_modified */
  1,   /* field[1] = key */
  7,   /* field[7] = pw */
  6,   /* field[6] = return_body */
  10,   /* field[10] = return_head */
  2,   /* field[2] = vclock */
  4,   /* field[4] = w */
};
static const ProtobufCIntRange rpb_put_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor rpb_put_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbPutReq",
  "RpbPutReq",
  "RpbPutReq",
  "",
  sizeof(RpbPutReq),
  11,
  rpb_put_req__field_descriptors,
  rpb_put_req__field_indices_by_name,
  1,  rpb_put_req__number_ranges,
  (ProtobufCMessageInit) rpb_put_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_put_resp__field_descriptors[3] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RpbPutResp, n_content),
    PROTOBUF_C_OFFSETOF(RpbPutResp, content),
    &rpb_content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbPutResp, has_vclock),
    PROTOBUF_C_OFFSETOF(RpbPutResp, vclock),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbPutResp, has_key),
    PROTOBUF_C_OFFSETOF(RpbPutResp, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_put_resp__field_indices_by_name[] = {
  0,   /* field[0] = content */
  2,   /* field[2] = key */
  1,   /* field[1] = vclock */
};
static const ProtobufCIntRange rpb_put_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_put_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbPutResp",
  "RpbPutResp",
  "RpbPutResp",
  "",
  sizeof(RpbPutResp),
  3,
  rpb_put_resp__field_descriptors,
  rpb_put_resp__field_indices_by_name,
  1,  rpb_put_resp__number_ranges,
  (ProtobufCMessageInit) rpb_put_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_del_req__field_descriptors[9] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbDelReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbDelReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rw",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_rw),
    PROTOBUF_C_OFFSETOF(RpbDelReq, rw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vclock",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_vclock),
    PROTOBUF_C_OFFSETOF(RpbDelReq, vclock),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_r),
    PROTOBUF_C_OFFSETOF(RpbDelReq, r),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_w),
    PROTOBUF_C_OFFSETOF(RpbDelReq, w),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_pr),
    PROTOBUF_C_OFFSETOF(RpbDelReq, pr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_pw),
    PROTOBUF_C_OFFSETOF(RpbDelReq, pw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbDelReq, has_dw),
    PROTOBUF_C_OFFSETOF(RpbDelReq, dw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_del_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  8,   /* field[8] = dw */
  1,   /* field[1] = key */
  6,   /* field[6] = pr */
  7,   /* field[7] = pw */
  4,   /* field[4] = r */
  2,   /* field[2] = rw */
  3,   /* field[3] = vclock */
  5,   /* field[5] = w */
};
static const ProtobufCIntRange rpb_del_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rpb_del_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbDelReq",
  "RpbDelReq",
  "RpbDelReq",
  "",
  sizeof(RpbDelReq),
  9,
  rpb_del_req__field_descriptors,
  rpb_del_req__field_indices_by_name,
  1,  rpb_del_req__number_ranges,
  (ProtobufCMessageInit) rpb_del_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_buckets_resp__field_descriptors[1] =
{
  {
    "buckets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbListBucketsResp, n_buckets),
    PROTOBUF_C_OFFSETOF(RpbListBucketsResp, buckets),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_buckets_resp__field_indices_by_name[] = {
  0,   /* field[0] = buckets */
};
static const ProtobufCIntRange rpb_list_buckets_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_list_buckets_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListBucketsResp",
  "RpbListBucketsResp",
  "RpbListBucketsResp",
  "",
  sizeof(RpbListBucketsResp),
  1,
  rpb_list_buckets_resp__field_descriptors,
  rpb_list_buckets_resp__field_indices_by_name,
  1,  rpb_list_buckets_resp__number_ranges,
  (ProtobufCMessageInit) rpb_list_buckets_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_keys_req__field_descriptors[1] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbListKeysReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_keys_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
};
static const ProtobufCIntRange rpb_list_keys_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_list_keys_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListKeysReq",
  "RpbListKeysReq",
  "RpbListKeysReq",
  "",
  sizeof(RpbListKeysReq),
  1,
  rpb_list_keys_req__field_descriptors,
  rpb_list_keys_req__field_indices_by_name,
  1,  rpb_list_keys_req__number_ranges,
  (ProtobufCMessageInit) rpb_list_keys_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_list_keys_resp__field_descriptors[2] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbListKeysResp, n_keys),
    PROTOBUF_C_OFFSETOF(RpbListKeysResp, keys),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbListKeysResp, has_done),
    PROTOBUF_C_OFFSETOF(RpbListKeysResp, done),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_list_keys_resp__field_indices_by_name[] = {
  1,   /* field[1] = done */
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange rpb_list_keys_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_list_keys_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbListKeysResp",
  "RpbListKeysResp",
  "RpbListKeysResp",
  "",
  sizeof(RpbListKeysResp),
  2,
  rpb_list_keys_resp__field_descriptors,
  rpb_list_keys_resp__field_indices_by_name,
  1,  rpb_list_keys_resp__number_ranges,
  (ProtobufCMessageInit) rpb_list_keys_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_bucket_req__field_descriptors[1] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbGetBucketReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_bucket_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
};
static const ProtobufCIntRange rpb_get_bucket_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_get_bucket_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetBucketReq",
  "RpbGetBucketReq",
  "RpbGetBucketReq",
  "",
  sizeof(RpbGetBucketReq),
  1,
  rpb_get_bucket_req__field_descriptors,
  rpb_get_bucket_req__field_indices_by_name,
  1,  rpb_get_bucket_req__number_ranges,
  (ProtobufCMessageInit) rpb_get_bucket_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_get_bucket_resp__field_descriptors[1] =
{
  {
    "props",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbGetBucketResp, props),
    &rpb_bucket_props__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_get_bucket_resp__field_indices_by_name[] = {
  0,   /* field[0] = props */
};
static const ProtobufCIntRange rpb_get_bucket_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_get_bucket_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbGetBucketResp",
  "RpbGetBucketResp",
  "RpbGetBucketResp",
  "",
  sizeof(RpbGetBucketResp),
  1,
  rpb_get_bucket_resp__field_descriptors,
  rpb_get_bucket_resp__field_indices_by_name,
  1,  rpb_get_bucket_resp__number_ranges,
  (ProtobufCMessageInit) rpb_get_bucket_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_set_bucket_req__field_descriptors[2] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbSetBucketReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "props",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbSetBucketReq, props),
    &rpb_bucket_props__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_set_bucket_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  1,   /* field[1] = props */
};
static const ProtobufCIntRange rpb_set_bucket_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_set_bucket_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbSetBucketReq",
  "RpbSetBucketReq",
  "RpbSetBucketReq",
  "",
  sizeof(RpbSetBucketReq),
  2,
  rpb_set_bucket_req__field_descriptors,
  rpb_set_bucket_req__field_indices_by_name,
  1,  rpb_set_bucket_req__number_ranges,
  (ProtobufCMessageInit) rpb_set_bucket_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_map_red_req__field_descriptors[2] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbMapRedReq, request),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbMapRedReq, content_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_map_red_req__field_indices_by_name[] = {
  1,   /* field[1] = content_type */
  0,   /* field[0] = request */
};
static const ProtobufCIntRange rpb_map_red_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_map_red_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbMapRedReq",
  "RpbMapRedReq",
  "RpbMapRedReq",
  "",
  sizeof(RpbMapRedReq),
  2,
  rpb_map_red_req__field_descriptors,
  rpb_map_red_req__field_indices_by_name,
  1,  rpb_map_red_req__number_ranges,
  (ProtobufCMessageInit) rpb_map_red_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_map_red_resp__field_descriptors[3] =
{
  {
    "phase",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, has_phase),
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, phase),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, has_response),
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, response),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "done",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, has_done),
    PROTOBUF_C_OFFSETOF(RpbMapRedResp, done),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_map_red_resp__field_indices_by_name[] = {
  2,   /* field[2] = done */
  0,   /* field[0] = phase */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange rpb_map_red_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_map_red_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbMapRedResp",
  "RpbMapRedResp",
  "RpbMapRedResp",
  "",
  sizeof(RpbMapRedResp),
  3,
  rpb_map_red_resp__field_descriptors,
  rpb_map_red_resp__field_indices_by_name,
  1,  rpb_map_red_resp__number_ranges,
  (ProtobufCMessageInit) rpb_map_red_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue rpb_index_req__index_query_type__enum_values_by_number[2] =
{
  { "eq", "RPB_INDEX_REQ__INDEX_QUERY_TYPE__EQ", 0 },
  { "range", "RPB_INDEX_REQ__INDEX_QUERY_TYPE__RANGE", 1 },
};
static const ProtobufCIntRange rpb_index_req__index_query_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex rpb_index_req__index_query_type__enum_values_by_name[2] =
{
  { "eq", 0 },
  { "range", 1 },
};
const ProtobufCEnumDescriptor rpb_index_req__index_query_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "RpbIndexReq.IndexQueryType",
  "IndexQueryType",
  "RpbIndexReq__IndexQueryType",
  "",
  2,
  rpb_index_req__index_query_type__enum_values_by_number,
  2,
  rpb_index_req__index_query_type__enum_values_by_name,
  1,
  rpb_index_req__index_query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpb_index_req__field_descriptors[6] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbIndexReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbIndexReq, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qtype",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbIndexReq, qtype),
    &rpb_index_req__index_query_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbIndexReq, has_key),
    PROTOBUF_C_OFFSETOF(RpbIndexReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_min",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbIndexReq, has_range_min),
    PROTOBUF_C_OFFSETOF(RpbIndexReq, range_min),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range_max",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbIndexReq, has_range_max),
    PROTOBUF_C_OFFSETOF(RpbIndexReq, range_max),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_index_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  1,   /* field[1] = index */
  3,   /* field[3] = key */
  2,   /* field[2] = qtype */
  5,   /* field[5] = range_max */
  4,   /* field[4] = range_min */
};
static const ProtobufCIntRange rpb_index_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpb_index_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbIndexReq",
  "RpbIndexReq",
  "RpbIndexReq",
  "",
  sizeof(RpbIndexReq),
  6,
  rpb_index_req__field_descriptors,
  rpb_index_req__field_indices_by_name,
  1,  rpb_index_req__number_ranges,
  (ProtobufCMessageInit) rpb_index_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_index_resp__field_descriptors[1] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbIndexResp, n_keys),
    PROTOBUF_C_OFFSETOF(RpbIndexResp, keys),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_index_resp__field_indices_by_name[] = {
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange rpb_index_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpb_index_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbIndexResp",
  "RpbIndexResp",
  "RpbIndexResp",
  "",
  sizeof(RpbIndexResp),
  1,
  rpb_index_resp__field_descriptors,
  rpb_index_resp__field_indices_by_name,
  1,  rpb_index_resp__number_ranges,
  (ProtobufCMessageInit) rpb_index_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_content__field_descriptors[10] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpbContent, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbContent, has_content_type),
    PROTOBUF_C_OFFSETOF(RpbContent, content_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "charset",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbContent, has_charset),
    PROTOBUF_C_OFFSETOF(RpbContent, charset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_encoding",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbContent, has_content_encoding),
    PROTOBUF_C_OFFSETOF(RpbContent, content_encoding),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vtag",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbContent, has_vtag),
    PROTOBUF_C_OFFSETOF(RpbContent, vtag),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "links",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RpbContent, n_links),
    PROTOBUF_C_OFFSETOF(RpbContent, links),
    &rpb_link__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_mod",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbContent, has_last_mod),
    PROTOBUF_C_OFFSETOF(RpbContent, last_mod),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_mod_usecs",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbContent, has_last_mod_usecs),
    PROTOBUF_C_OFFSETOF(RpbContent, last_mod_usecs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usermeta",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RpbContent, n_usermeta),
    PROTOBUF_C_OFFSETOF(RpbContent, usermeta),
    &rpb_pair__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexes",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RpbContent, n_indexes),
    PROTOBUF_C_OFFSETOF(RpbContent, indexes),
    &rpb_pair__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_content__field_indices_by_name[] = {
  2,   /* field[2] = charset */
  3,   /* field[3] = content_encoding */
  1,   /* field[1] = content_type */
  9,   /* field[9] = indexes */
  6,   /* field[6] = last_mod */
  7,   /* field[7] = last_mod_usecs */
  5,   /* field[5] = links */
  8,   /* field[8] = usermeta */
  0,   /* field[0] = value */
  4,   /* field[4] = vtag */
};
static const ProtobufCIntRange rpb_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor rpb_content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbContent",
  "RpbContent",
  "RpbContent",
  "",
  sizeof(RpbContent),
  10,
  rpb_content__field_descriptors,
  rpb_content__field_indices_by_name,
  1,  rpb_content__number_ranges,
  (ProtobufCMessageInit) rpb_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_link__field_descriptors[3] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbLink, has_bucket),
    PROTOBUF_C_OFFSETOF(RpbLink, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbLink, has_key),
    PROTOBUF_C_OFFSETOF(RpbLink, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(RpbLink, has_tag),
    PROTOBUF_C_OFFSETOF(RpbLink, tag),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_link__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  1,   /* field[1] = key */
  2,   /* field[2] = tag */
};
static const ProtobufCIntRange rpb_link__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpb_link__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbLink",
  "RpbLink",
  "RpbLink",
  "",
  sizeof(RpbLink),
  3,
  rpb_link__field_descriptors,
  rpb_link__field_indices_by_name,
  1,  rpb_link__number_ranges,
  (ProtobufCMessageInit) rpb_link__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpb_bucket_props__field_descriptors[2] =
{
  {
    "n_val",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(RpbBucketProps, has_n_val),
    PROTOBUF_C_OFFSETOF(RpbBucketProps, n_val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allow_mult",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(RpbBucketProps, has_allow_mult),
    PROTOBUF_C_OFFSETOF(RpbBucketProps, allow_mult),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpb_bucket_props__field_indices_by_name[] = {
  1,   /* field[1] = allow_mult */
  0,   /* field[0] = n_val */
};
static const ProtobufCIntRange rpb_bucket_props__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpb_bucket_props__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpbBucketProps",
  "RpbBucketProps",
  "RpbBucketProps",
  "",
  sizeof(RpbBucketProps),
  2,
  rpb_bucket_props__field_descriptors,
  rpb_bucket_props__field_indices_by_name,
  1,  rpb_bucket_props__number_ranges,
  (ProtobufCMessageInit) rpb_bucket_props__init,
  NULL,NULL,NULL    /* reserved[123] */
};
