/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: riak_search.proto */

#ifndef PROTOBUF_C_riak_5fsearch_2eproto__INCLUDED
#define PROTOBUF_C_riak_5fsearch_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "riak.pb-c.h"

typedef struct _RpbSearchDoc RpbSearchDoc;
typedef struct _RpbSearchQueryReq RpbSearchQueryReq;
typedef struct _RpbSearchQueryResp RpbSearchQueryResp;


/* --- enums --- */


/* --- messages --- */

struct  _RpbSearchDoc
{
  ProtobufCMessage base;
  size_t n_fields;
  RpbPair **fields;
};
#define RPB_SEARCH_DOC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpb_search_doc__descriptor) \
    , 0,NULL }


struct  _RpbSearchQueryReq
{
  ProtobufCMessage base;
  ProtobufCBinaryData q;
  ProtobufCBinaryData index;
  protobuf_c_boolean has_rows;
  uint32_t rows;
  protobuf_c_boolean has_start;
  uint32_t start;
  protobuf_c_boolean has_sort;
  ProtobufCBinaryData sort;
  protobuf_c_boolean has_filter;
  ProtobufCBinaryData filter;
  protobuf_c_boolean has_df;
  ProtobufCBinaryData df;
  protobuf_c_boolean has_op;
  ProtobufCBinaryData op;
  size_t n_fl;
  ProtobufCBinaryData *fl;
  protobuf_c_boolean has_presort;
  ProtobufCBinaryData presort;
};
#define RPB_SEARCH_QUERY_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpb_search_query_req__descriptor) \
    , {0,NULL}, {0,NULL}, 0,0, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,NULL, 0,{0,NULL} }


struct  _RpbSearchQueryResp
{
  ProtobufCMessage base;
  size_t n_docs;
  RpbSearchDoc **docs;
  protobuf_c_boolean has_max_score;
  float max_score;
  protobuf_c_boolean has_num_found;
  uint32_t num_found;
};
#define RPB_SEARCH_QUERY_RESP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpb_search_query_resp__descriptor) \
    , 0,NULL, 0,0, 0,0 }


/* RpbSearchDoc methods */
void   rpb_search_doc__init
                     (RpbSearchDoc         *message);
size_t rpb_search_doc__get_packed_size
                     (const RpbSearchDoc   *message);
size_t rpb_search_doc__pack
                     (const RpbSearchDoc   *message,
                      uint8_t             *out);
size_t rpb_search_doc__pack_to_buffer
                     (const RpbSearchDoc   *message,
                      ProtobufCBuffer     *buffer);
RpbSearchDoc *
       rpb_search_doc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpb_search_doc__free_unpacked
                     (RpbSearchDoc *message,
                      ProtobufCAllocator *allocator);
/* RpbSearchQueryReq methods */
void   rpb_search_query_req__init
                     (RpbSearchQueryReq         *message);
size_t rpb_search_query_req__get_packed_size
                     (const RpbSearchQueryReq   *message);
size_t rpb_search_query_req__pack
                     (const RpbSearchQueryReq   *message,
                      uint8_t             *out);
size_t rpb_search_query_req__pack_to_buffer
                     (const RpbSearchQueryReq   *message,
                      ProtobufCBuffer     *buffer);
RpbSearchQueryReq *
       rpb_search_query_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpb_search_query_req__free_unpacked
                     (RpbSearchQueryReq *message,
                      ProtobufCAllocator *allocator);
/* RpbSearchQueryResp methods */
void   rpb_search_query_resp__init
                     (RpbSearchQueryResp         *message);
size_t rpb_search_query_resp__get_packed_size
                     (const RpbSearchQueryResp   *message);
size_t rpb_search_query_resp__pack
                     (const RpbSearchQueryResp   *message,
                      uint8_t             *out);
size_t rpb_search_query_resp__pack_to_buffer
                     (const RpbSearchQueryResp   *message,
                      ProtobufCBuffer     *buffer);
RpbSearchQueryResp *
       rpb_search_query_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpb_search_query_resp__free_unpacked
                     (RpbSearchQueryResp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RpbSearchDoc_Closure)
                 (const RpbSearchDoc *message,
                  void *closure_data);
typedef void (*RpbSearchQueryReq_Closure)
                 (const RpbSearchQueryReq *message,
                  void *closure_data);
typedef void (*RpbSearchQueryResp_Closure)
                 (const RpbSearchQueryResp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rpb_search_doc__descriptor;
extern const ProtobufCMessageDescriptor rpb_search_query_req__descriptor;
extern const ProtobufCMessageDescriptor rpb_search_query_resp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_riak_5fsearch_2eproto__INCLUDED */
